name = "demo-webserver"
description = "standard apache httpd webserver"
version = "1.0.3"
distro = "rhel-94"

[[packages]]
name = "tmux"
version = "3.2a"

[[packages]]
name = "httpd"
version = "*"

[[customizations.user]]
name = "ogren"
password = "$6$olmomMEyXF2CY3Fw$zWHZVhwU9rLmZ2wVi3IdVZD0dgDc7K0Dn1ChKIHbwARehvQkJdWNDrtDDTb4JyoCCBuzOQFFG2PVlVbGAzGUV."
shell = "/usr/bin/bash"

[customizations.services]
enabled = ["sshd", "httpd"]

[customizations.firewall.services]
enabled = ["httpd:tcp"]