name = "demo-webserver"
description = "standard apache httpd webserver"
version = "1.0.6"
distro = "rhel-8"

[[packages]]
name = "tmux"
version = "2.7"

[[packages]]
name = "httpd"
version = "*"

[[customizations.user]]
name = "ogren"
password = "$6$olmomMEyXF2CY3Fw$zWHZVhwU9rLmZ2wVi3IdVZD0dgDc7K0Dn1ChKIHbwARehvQkJdWNDrtDDTb4JyoCCBuzOQFFG2PVlVbGAzGUV."
shell = "/usr/bin/bash"

[customizations.firewall.services]
enabled = ["http"]