name = "demo-webserver"
description = "standard apache httpd webserver"
version = "1.0"
distro = "rhel-94"

[[packages]]
name = "tmux"
version = "3.2a"

[[packages]]
name = "httpd"
version = "2.4.57-8"

[customizations.firewall.services]
ports = ["https:tcp"]

[customizations.firewall.services]
enabled = ["sshd", "httpd"]
disabled = ["postfix", "telnetd"]