name = "demo-postgres"
description = ""
version = "0.0.3"

[[packages]]
name = "postgresql"

[[packages]]
name = "postgresql-server"

[[packages]]
name = "tuned-profiles-postgresql"

[customizations.firewall.services]
ports = ["5432"]
